version: '3.7'
services:  
  redis:
    image: redis
    container_name: redisTask 
  mongo:
    image: mongo
    container_name: mongoTask 
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGO_URL=mongodb://mongoTask:27017/nest